#define ENCODER_A_PINS { GP28 }
#define ENCODER_B_PINS { GP27 }

#define VIAL_KEYBOARD_UID {0x29, 0xB1, 0xCB, 0x5A, 0x6D, 0xEE, 0xC5, 0xFE}

#define VIAL_UNLOCK_COMBO_ROWS { 0, 0 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 1 }
